spring:
  application:
    name: ${APP_NAME:libraryApi}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/library}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      "[hibernate.format_sql]": true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}

server:
  port: ${SERVER_PORT:8080}

app:
  security:
    default-password: ${DEFAULT_PASSWORD:123456}
    jwt-secret: ${JWT_SECRET:mySecretKey123456789}

#niveis de log
#trace - mais detalhado (nao recomendado para producao)
#debug - detalhado (nao recomendado para producao)
#info - informativo (recomendado para producao)
#warn - aviso (recomendado para producao)
#error - erro (recomendado para producao)
#fatal - fatal (recomendado para producao)

logging:
  file:
    name: app.log
  level:
    root: warn
    io:
      github:
        dotyocode:
          libraryApi: trace
    org:
      springframework:
        web: debug
